# Constants
INTERNAL_NAMESPACE = 'internal'
CHANGE_LOG_TABLE = 'change_log'
SYSTEM_USER_NAME = 'SYSTEM'
SNAPSHOT_TABLE = 'snapshot'
DEFAULT_NAMESPACE = 'public'
PRISM_PORT = 20591
WEBUI_PORT = 8080
HTTP_PORT = 80
CONFIG_SERVER_PORT = 8081
INFORMATION_SERVER_PORT = 8082
SCHEMA_SNAPSHOT_NAME = 'schema.mappingsnap'

# Derived Variables
CHANGE_LOG_IDENTIFIER = f'{INTERNAL_NAMESPACE}.{CHANGE_LOG_TABLE}'

