name: Run Tests

on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"

jobs:
  test:
    name: Run pytest (with Docker)
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:20.10.16
        options: >-
          --privileged
        ports:
          - 20590:20590
          - 7659:7659
          - 80:80
          - 8081:8081
          - 8082:8082

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Install Docker CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y docker.io
          sudo systemctl start docker
          docker --version

      - name: Add GitHub Actions user to docker group
        run: |
          sudo usermod -aG docker $USER

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: pytest
